POST http://localhost:8080/api/mcp-rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "initialize",
  "params": {
    "protocolVersion": "2024-11-05",
    "capabilities": {
      "roots": {
        "listChanged": true
      },
      "sampling": {},
      "elicitation": {}
    },
    "clientInfo": {
      "name": "TestHttpClient",
      "title": "Example Client Display Name",
      "version": "1.0.0"
    }
  }
}